version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'mydb'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - fmdb:/var/lib/mysql

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: fmdb
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    command: ["npx", "nx", "serve", "server"]

  webpage:
    build:
      context: .
      dockerfile: Dockerfile.webpage
    depends_on:
      - server
    ports:
      - "4200:4200"
    volumes:
      - .:/app
    command: ["npx", "nx", "serve", "webpage"]

volumes:
  fmdb:
