FROM node:23-slim

# Set working directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Clean and install dependencies
RUN rm -rf node_modules package-lock.json && npm install --no-optional

# Copy everything
COPY . .

# Expose and run
EXPOSE 3000
CMD ["npx", "nx", "serve", "server"] 
