version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'mydb'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3307:3306'
    volumes:
      - mydb:/var/lib/mysql

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    depends_on:
      - db
    environment:
      DB_PORT: 3306
      DB_NAME: mydb
      DB_PASSWORD: root
    ports:
      - "3001:3000"
    volumes:
      - .:/app
    command: ["npx", "nx", "serve", "server"]

  webpage:
    build:
      context: .
      dockerfile: Dockerfile.webpage
    depends_on:
      - server
    ports:
      - "4201:4200"
    volumes:
      - .:/app
    command: ["npx", "nx", "serve", "webpage"]

volumes:
  mydb:
